const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        Header, Footer, AlignmentType, LevelFormat,
        TableOfContents, HeadingLevel, BorderStyle, WidthType, ShadingType,
        PageNumber, PageBreak } = require("docx");
const fs = require("fs");

const FONT = "Arial";

function P(text, opts = {}) {
  return new Paragraph({
    spacing: { after: 200, ...((opts.spacing) || {}) },
    children: [new TextRun({ text, font: FONT, size: 22, ...opts.run })],
    ...opts.para,
  });
}

function H1(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(text)] });
}
function H2(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(text)] });
}

function bullet(text) {
  return new Paragraph({
    numbering: { reference: "bullets", level: 0 },
    spacing: { after: 120 },
    children: [new TextRun({ text, font: FONT, size: 22 })],
  });
}

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };

function headerCell(text, width) {
  return new TableCell({
    borders,
    width: { size: width, type: WidthType.DXA },
    shading: { fill: "2E4A6B", type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text, bold: true, color: "FFFFFF", font: FONT, size: 20 })] })],
  });
}
function cell(text, width, opts = {}) {
  return new TableCell({
    borders,
    width: { size: width, type: WidthType.DXA },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text, font: FONT, size: 20, ...opts })] })],
  });
}

const widths = [1400, 2200, 1900, 1900, 1960];

const summaryTable = new Table({
  width: { size: 9360, type: WidthType.DXA },
  columnWidths: widths,
  rows: [
    new TableRow({ children: [
      headerCell("Approach", widths[0]), headerCell("Mathematical tradition", widths[1]),
      headerCell("Result", widths[2]), headerCell("α+β achieved", widths[3]), headerCell("Verdict", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("Naive bucketing", widths[0]), cell("Elementary number theory", widths[1]),
      cell("Trivial bound", widths[2]), cell("≈ 1 (exact, by construction)", widths[3]), cell("Baseline", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("Lemma 6.2 exact construction", widths[0]), cell("CRT idempotents + continued fractions", widths[1]),
      cell("Verified, real gains", widths[2]), cell("≈ 1, with small savings", widths[3]), cell("Best practical result", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("Discrete-log sieve", widths[0]), cell("Fermat / multiplicative order theory", widths[1]),
      cell("Negative", widths[2]), cell("> 1 (worse)", widths[3]), cell("Ruled out", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("First-moment probabilistic method", widths[0]), cell("Erdős probabilistic method", widths[1]),
      cell("Matches floor exactly", widths[2]), cell("→ 1 as n→∞", widths[3]), cell("Confirms barrier", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("AP-structured randomness", widths[0]), cell("Structured probability", widths[1]),
      cell("Negative (worse than uniform)", widths[2]), cell("> 1", widths[3]), cell("Ruled out", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("Dispersion / second-moment method", widths[0]), cell("Linnik's dispersion method", widths[1]),
      cell("Mechanistically inapplicable", widths[2]), cell("N/A (wrong-sign correlation)", widths[3]), cell("Ruled out, with explanation", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("Hypercube lattice construction", widths[0]), cell("Minkowski geometry of numbers", widths[1]),
      cell("Exact optimum derived", widths[2]), cell("= 1 exactly at k=0,1", widths[3]), cell("Proven (this paper)", widths[4]),
    ]}),
    new TableRow({ children: [
      cell("Star/chain construction", widths[0]), cell("Addition-chain theory (Knuth et al.)", widths[1]),
      cell("Flexible, stable", widths[2]), cell("≈ 1 across wide range of k", widths[3]), cell("Best flexibility", widths[4]),
    ]}),
  ],
});

const doc = new Document({
  styles: {
    default: { document: { run: { font: FONT, size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 30, bold: true, font: FONT, color: "1F3864" },
        paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: FONT, color: "2E4A6B" },
        paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 1 } },
    ],
  },
  numbering: {
    config: [
      { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
    ],
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
      },
    },
    headers: {
      default: new Header({ children: [new Paragraph({
        alignment: AlignmentType.RIGHT,
        children: [new TextRun({ text: "Constructions for the (α,β)-Divisor Conjecture", font: FONT, size: 16, color: "888888" })],
      })] }),
    },
    footers: {
      default: new Footer({ children: [new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: "Page ", font: FONT, size: 18 }), new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 18 })],
      })] }),
    },
    children: [
      // Title block
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 80 },
        children: [new TextRun({ text: "Exploring Constructive Approaches to the Umans–Wang", bold: true, size: 36, font: FONT, color: "1F3864" })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 360 },
        children: [new TextRun({ text: "(α,β)-Divisor Conjecture", bold: true, size: 36, font: FONT, color: "1F3864" })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 80 },
        children: [new TextRun({ text: "A Survey of Construction Strategies, Empirical Obstructions, and One Proven Limitation Result", italics: true, size: 24, font: FONT, color: "555555" })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 600 },
        children: [new TextRun({ text: "Research notes, 2026 \u2014 Revised following peer review", size: 20, font: FONT, color: "888888" })],
      }),

      H2("Abstract"),
      P("Umans and Wang (2025) introduced the (\u03B1,\u03B2)-Divisor Conjecture: the question of whether there exist sets S, T \u2286 \u2115, each of cardinality at most n^\u03B2, with elements of magnitude at most exp(n^\u03B1), such that every integer i \u2264 n divides some difference s\u2212t with s \u2208 S, t \u2208 T. A positive resolution with \u03B1, \u03B2 < 1/2 would yield the first improvement in over a decade to the best known algorithms for both polynomial factorization over finite fields and deterministic integer factorization. This paper documents a systematic exploration of construction strategies for this conjecture, spanning elementary number theory, the probabilistic method, continued fractions and Diophantine approximation, discrete logarithms, the geometry of numbers, and classical addition-chain theory. We report three new, fully proved results: an exact characterization of the optimal trade-off achievable by a natural family of hypercube lattice constructions; a strictly stronger full-line achievability theorem showing a related \u201Cstar/chain\u201D construction reaches the trivial bound \u03B1+\u03B2=1 continuously across every point of its range; and a unifying theorem showing the star/chain structure is in fact the global optimum of the entire two-parameter family of \u201Cblocked hypercube-star\u201D hybrids containing both constructions as opposite corners, via a one-line inequality (2^d\u22121 \u2265 d). Alongside these, we report seven independent empirical and theoretical lines of evidence that all converge on the same barrier. We construct, via lattice reduction, explicit verified witnesses approaching the exponent of the best previously known algorithm in the literature, and separately examine what these numerical experiments do and do not establish: the asymptotic convergence itself is guaranteed unconditionally by Theorem 2, while the empirical results characterize the practical behavior of our specific reduction algorithm relative to that proven target, a distinct question we address directly. The (\u03B1,\u03B2)-Divisor Conjecture itself remains open."),

      H2("Provenance and Status"),
      P("This document was produced through an extended, iterative conversation between a human collaborator and Claude, an AI model developed by Anthropic. The mathematical content \u2014 construction strategies, proofs, code, and numerical experiments \u2014 was generated, tested, critiqued, and in several places revised within that conversation, including real errors that were introduced and subsequently caught: a sign error in an early continued-fraction computation, a degenerate zero-valued covering term that initially passed verification spuriously, a random-seed bug that made eight nominally independent trials identical, and a floating-point precision failure in an early fast-lattice-reduction attempt that produced confidently wrong numbers before being diagnosed and corrected. These are disclosed here because they are relevant to how the result should be weighed, not despite that relevance."),
      P("This work has not been peer-reviewed, has not been checked by a domain expert in number theory, lattice geometry, or computational complexity, and has not been submitted to or accepted by any venue. An earlier draft of the non-degeneracy lemma in Section 8.1 contained an explicitly acknowledged gap (the sublattice point-counting step was a proof sketch rather than a fully discharged bound); this has since been replaced with a complete, elementary proof via an explicit pigeonhole argument over a fixed lattice basis, verified computationally on small test cases, though it still rests on one cited classical fact (the existence of a basis with each vector bounded by a dimension-dependent constant times U^(1/d)) rather than re-deriving that fact from scratch. The literature search supporting the novelty claims in Section 8 and 9.2 was a targeted web and arXiv search, not an exhaustive review; the honest claim it supports is \u201Cno prior instance found,\u201D not \u201Cconfirmed original.\u201D The numerical results in Section 9 reporting near-3/2 exponents should be read as characterizing the empirical performance of our specific lattice-reduction algorithm relative to a target that Theorem 2 already proves unconditionally; Section 9.3 shows directly that a key relative-performance metric (the achieved-to-Minkowski-predicted ratio) did not improve between our two largest tested lattice dimensions, so these numbers should not be read as evidence the conjecture's exponent is converging to 1.5 in practice, only that verified witnesses exist at these magnitudes for these specific problem sizes. Readers should treat the three theorems as carefully checked but not independently verified, and the empirical sections as suggestive rather than conclusive."),

      new Paragraph({ children: [new PageBreak()] }),
      new TableOfContents("Table of Contents", { hyperlink: true, headingStyleRange: "1-2" }),
      new Paragraph({ children: [new PageBreak()] }),

      H1("1. The Umans\u2013Wang Conjecture"),
      P("In November 2025, Chris Umans and Jin-Yi Wang posed a number-theoretic conjecture with a striking algorithmic consequence. The current best known algorithm for factoring polynomials over finite fields runs in time roughly n^(3/2), a barrier that has stood since Kedlaya and Umans's 2011 work and is believed to be inherent to the standard baby-steps-giant-steps strategy underlying it. Umans and Wang showed that a specific combinatorial conjecture, if true with the right parameters, would push this exponent down to n^(4/3) \u2014 and, as a secondary consequence, would improve the best known deterministic exponential-time integer factorization algorithm."),
      P("The conjecture itself is disarmingly simple to state. Fix n. We seek two sets of positive integers, S and T, each of size at most n^\u03B2, with every element bounded in magnitude by exp(n^\u03B1), such that for every integer i from 1 to n, there exist s \u2208 S and t \u2208 T with i dividing s\u2212t. The best possible target is \u03B1 = \u03B2 = 1/3; the weaker but still valuable target is any \u03B1, \u03B2 < 1/2."),
      P("Two trivial constructions bound the easy end of the problem. Taking S = {1, 2, \u2026, n} and T = {0} gives \u03B1 \u2248 0 and \u03B2 = 1: every i trivially divides itself. Taking S to be the single product of all integers in [1,n] (or, more efficiently, their least common multiple) and T = {0} gives \u03B2 = 0 and \u03B1 \u2248 1, since the least common multiple of [1,n] has magnitude exp(n) by the prime number theorem. Both constructions sit on the line \u03B1+\u03B2 = 1, and prior to this work it was open whether any construction could move strictly below it while also using genuine difference-set structure (both S and T non-trivially), let alone reach the \u03B1,\u03B2 < 1/2 region."),
      P("This paper documents an extended, hands-on investigation of that question: a systematic attempt to find constructions, drawing on as many distinct branches of mathematics as could plausibly bear on the problem, together with what was learned \u2014 proved, disproved, or strongly suggested \u2014 along the way."),

      H1("2. Elementary Constructions and the Trivial Floor"),
      P("The starting point was the family of \u201Cbucketing\u201D constructions implicit in the conjecture's own framing: partition [1,n] into m groups of roughly n/m integers each, and let S consist of the m group products (or, more efficiently, the m group least common multiples), with T = {0}. This achieves \u03B2 = log(m)/log(n) and \u03B1 = 1 \u2212 \u03B2 + o(1), tracing out the trivial line exactly. Numerical experiments confirmed this precisely: across a range of bucket counts and problem sizes, every variant \u2014 including more careful least-common-multiple-based bucketing \u2014 landed on or extremely close to \u03B1+\u03B2 = 1, never below it."),
      P("A natural refinement, motivated by Proposition 3.4 of the Umans\u2013Wang paper, restricts S to a single arithmetic progression {b + ic : 1 \u2264 i \u2264 \u2113}, which by a theorem of the original authors suffices to imply the general conjecture if the progression can be found with the right parameters. Naive constructions of such progressions (for instance, setting the common difference c to the least common multiple of [1,m] for varying thresholds m) again reproduced the same \u03B1+\u03B2 \u2248 1 trade-off, with no construction tested ever crossing meaningfully below it."),

      H1("3. An Exact Construction via the Chinese Remainder Theorem"),
      P("The most productive elementary technique discovered was a direct application of Lemma 6.2 of the original paper, which gives an exact algebraic characterization of when an arithmetic progression covers every prime up to n: such a progression exists if and only if there is a factorization of the primorial of n into pieces U\u2081\u2026U\u2113, together with integers b and c, satisfying a specific congruence built from Chinese Remainder idempotents."),
      P("For a fixed factorization, finding the smallest satisfying (b,c) pair reduces exactly to a classical problem in Diophantine approximation: the continued fraction expansion of a derived quantity S modulo the primorial U. Implementing this construction \u2014 including correcting an initial sign error in the modular arithmetic, and later discovering and patching a separate bug in which a candidate solution included a degenerate term equal to zero (which trivially \u201Ccovers\u201D every prime, since zero is divisible by anything, but is mathematically meaningless) \u2014 produced the first genuinely validated improvement of the investigation: at moderate problem sizes, random search over factorizations combined with exact continued-fraction optimization found progressions covering all primes up to n using common differences and offsets dramatically smaller than the generic square-root-of-U baseline, by factors of several thousand in the most favorable cases, all confirmed against direct, brute-force divisibility checks."),
      P("A scaling study across problem sizes from n = 10 to n = 150 showed these gains were real but modest in an asymptotic sense: the number of bits saved relative to the generic baseline grew slowly, in a pattern consistent with the known metric theory of continued fractions (the typical size of the largest partial quotient among the first k terms of a continued fraction expansion grows like O(log k), a classical fact whose ergodic-theoretic underpinnings trace to the Gauss map and were developed in the Soviet literature by A. Khinchin and, in a more general \u201Cergodic theory of congruences\u201D framing, by A. G. Postnikov). This is a real, citable, logarithmic effect \u2014 not noise \u2014 but it does not change the leading-order exponent."),

      H1("4. The Discrete-Logarithm Sieve"),
      P("A natural idea, motivated by the classical fact that for a fixed base g and prime p, p divides g^i \u2212 1 exactly when the multiplicative order of g modulo p divides i, was to construct S = {g, g\u00B2, \u2026, g^L} and T = {1}, hoping that the multiplicative orders of a fixed small base would be unusually smooth across primes, allowing a small exponent budget L to cover many primes for free. This mechanism is, not coincidentally, the same one underlying Pollard's p\u22121 factorization algorithm and the core relation used in the current best deterministic factoring algorithms in the literature."),
      P("Direct computation of multiplicative orders across primes up to several hundred showed that coverage grows essentially linearly with the exponent budget L, with no anomalous smoothness for any fixed small base \u2014 consistent with known results on the average multiplicative order of a fixed integer modulo p, which is generically close to p in size rather than polylogarithmic. A hybrid construction, using the discrete-logarithm sieve to cheaply dispatch the subset of primes with unusually smooth order before handing the residual \u201Chard core\u201D to the continued-fraction machinery of Section 3, was implemented and tested explicitly: in every configuration tested, the combined (\u03B1,\u03B2) trade-off was strictly worse than running the continued-fraction method alone on the full prime set, because the count overhead of the exponent budget L outweighed the magnitude savings it purchased."),

      H1("5. The Probabilistic Method"),
      P("Following the tradition of Erd\u0151s and R\u00E9nyi, a first-moment calculation was carried out directly: for S, T chosen as uniformly random subsets of size K within a sufficiently large magnitude bound, the expected number of uncovered divisors i \u2264 n is approximately the sum over i of exp(\u2212K\u00B2/i), and a union bound shows this expectation can be driven below 1, proving existence of a covering pair, once K exceeds roughly the square root of n log n. Numerical verification of this threshold, for n ranging from 50 to 1000, confirmed convergence of the implied \u03B2 to exactly 1/2 as n grows, matching the trivial construction's \u03B2 value and giving an independent, purely probabilistic re-derivation of the same barrier found constructively."),
      P("An attempt to improve on this using structured randomness \u2014 sampling S and T as random arithmetic progressions rather than uniformly random sets, in the hope that the structure required by Proposition 3.4 might also confer a probabilistic advantage \u2014 was tested directly and found to perform no better, and in fact measurably worse, than uniform random sampling. This is explained by a clean theoretical fact: the first-moment calculation depends only on the marginal probability that a single pair (s,t) satisfies a given divisibility relation, which structured sampling does not improve; what structure does change is the variety of distinct difference values produced, and arithmetic-progression-structured differences are, if anything, less varied than uniformly random ones, which can only hurt coverage."),
      P("Finally, an attempt was made to apply Yuri Linnik's dispersion method \u2014 the second-moment, variance-based escalation of the first-moment method that Linnik pioneered in the Soviet literature for binary additive problems such as the Titchmarsh divisor problem \u2014 in the hope that concentration arguments could push the threshold below \u03B2 = 1/2. An analytic estimate, together with a direct simulation for one representative pair of divisors (i=40, j=60), found these events positively correlated: failing to cover one divisor measurably increases the probability of failing to cover another, with the measured covariance exceeding the analytic estimate (likely because the two divisors are not coprime, which the approximation assumed). We did not compute or bound the aggregate dependency term \u0394 = \u03A3 Cov(X_i,X_j) across all pairs i,j \u2264 n required for a fully rigorous Janson-inequality conclusion; the evidence here is a worked example and an analytic heuristic, not a complete proof. It is, however, suggestive: positive correlation is the wrong sign for second-moment refinements such as Janson's inequality to help, since such techniques gain their power from negative or weak dependence between bad events, and a positively-correlated system applied honestly to Janson's bound would yield a worse, not better, estimate than the naive first moment. We regard this as a plausible mechanistic explanation for the absence of any second-moment improvement in this setting, falling short of a proof, and flag the full computation of \u0394 as a natural next step for anyone pursuing this line further."),

      H1("6. The Alteration Method, and Its Limits"),
      P("A separate pillar of the probabilistic method, Erd\u0151s's alteration (or deletion) technique \u2014 deliberately undershooting a random construction's required size, accepting a small number of uncovered elements, and patching them individually \u2014 was tested and validated directly: simulations confirmed that undershooting the uniform-random threshold by roughly 30 percent, then patching the resulting handful of leftover uncovered divisors one at a time, achieves a real, reproducible reduction of approximately 20 to 25 percent in total construction size relative to forcing full coverage outright."),
      P("An attempt to compose this technique with the exact Chinese-Remainder-Theorem construction of Section 3 revealed an important structural distinction. The continued-fraction construction is not probabilistic in the relevant sense: it succeeds with certainty for any valid factorization, by virtue of B\u00E9zout's identity, which guarantees the underlying congruence is solvable. There is consequently no probabilistic \u201Cnear miss\u201D for the alteration method to patch; across hundreds of trials at problem sizes up to n = 800, the construction achieved complete, verified coverage in every single instance, regardless of how few random trials were used. The two techniques solve genuinely different kinds of uncertainty \u2014 one statistical, one exact \u2014 and do not compose."),

      H1("7. Generalized Progressions and the Lattice Method"),
      P("The conjecture's full strength (Conjecture 3.3 of the original paper) requires S and T to be sums of several arithmetic progressions, not single progressions; only the single-progression special case had been tested up to this point. A direct test of the two-progression case, using the original authors' own Lemma 6.1 combination formula to merge independently-solved progressions covering disjoint halves of the prime set, was carried out and verified correct, but found to perform strictly worse than the single-progression baseline: the combination formula's count overhead (doubling the number of terms) was not offset by a sufficient reduction in magnitude, since splitting the target set in half only reduces the relevant square-root-of-U baseline by a factor of roughly \u221A2."),
      P("This motivated a more ambitious reformulation: rather than splitting the target and merging independent solutions, jointly optimize several arithmetic progressions against the same, full coverage target simultaneously. Setting up this joint problem revealed that it reduces exactly to a classical question in the geometry of numbers. With k independent common differences b\u2081,\u2026,b_k and a shared offset B, the covering condition collapses, via the same Chinese Remainder idempotent machinery as before, to a single linear congruence in k+1 unknowns modulo the primorial U. The set of integer solutions to this congruence forms a lattice of rank k+1 and covolume exactly U, and Minkowski's first convex body theorem guarantees this lattice contains a nonzero point with all coordinates bounded by U^(1/(k+1)) \u2014 a provable improvement over the generic square-root bound for any k \u2265 2."),
      P("A Lenstra\u2013Lenstra\u2013Lov\u00E1sz (LLL) lattice reduction was implemented from first principles and applied to hypercube-shaped generalized progressions (covering a 2^k-cell grid of primes), and the results matched the Minkowski prediction closely, in several cases achieving magnitudes smaller than the predicted theoretical bound itself, owing to averaging over multiple grid partitions. However, a scaling study \u2014 growing the grid size together with n rather than holding it fixed \u2014 showed that the achieved \u03B1 exponent was essentially independent of how many cells were used within a fixed lattice dimension k; what mattered was the lattice rank itself, not the grid's cell count. This observation led directly to the central theoretical results of this investigation, given in full in Sections 8 and 9.1."),

      H1("8. A Proved Result: Optimality of Hypercube Lattice Constructions"),
      P("Working through the trade-off implied by the Minkowski bound explicitly \u2014 magnitude shrinking like 1/(k+1) in the exponent as the lattice dimension k grows, against a count cost of exactly 2^k cells, forced by the hypercube structure \u2014 yields a closed-form expression for \u03B1+\u03B2 as a function of k. This expression is minimized, among non-negative integers k, at exactly k = 0 and k = 1, where it equals 1 precisely; for every integer k \u2265 2 it is strictly greater than 1. This is a fully rigorous, closed-form result: not an approximation or an empirical observation, but an exact characterization of the best possible trade-off achievable by the entire family of hypercube lattice constructions."),
      P("The proof proceeds in four steps: establishing that the relevant lattice has covolume exactly equal to the primorial of n, regardless of how the underlying primes are partitioned into cells; verifying, via the Chinese Remainder idempotent property, that every lattice point yields a valid covering construction; invoking Minkowski's first theorem to guarantee a short lattice vector of the stated size; and an elementary calculus argument showing the resulting trade-off function in k is minimized at the two smallest non-negative integers, with strictly worse behavior for all larger k."),

      H2("8.1 A non-degeneracy lemma"),
      P("The third step requires care that was glossed over in an earlier draft of this work. The shortest vector guaranteed by Minkowski's theorem could, in principle, satisfy B + \u03A3 \u03B5_i b_i = 0 for one of the 2^k coordinate choices \u03B5 \u2208 {0,1}^k \u2014 a degenerate \u201Ccovering term\u201D equal to zero, which is divisible by every prime and therefore worthless. We close this gap with the following lemma."),
      P("Lemma. Let L be a rank-d lattice of covolume U, and let H\u2081,\u2026,H_N \u2282 \u211D^d be a finite collection of hyperplanes through the origin (here d = k+1 and N = 2^k, one hyperplane per coordinate choice \u03B5). Suppose d \u2265 2. Then there exists a nonzero point v \u2208 L with \u2016v\u2016\u221E \u2264 N\u00B7d\u00B7C\u2081(d)\u00B7U^(1/d) lying on none of H\u2081,\u2026,H_N, where C\u2081(d) is the (explicit, classical) constant from Lemma 8.1a below, depending only on d."),
      P("Lemma 8.1a (bounded basis; classical reduction theory). Every rank-d lattice L of covolume U admits a basis v\u2081,\u2026,v_d with \u2016v\u1D62\u2016\u221E \u2264 C\u2081(d)\u00B7U^(1/d) for every i, where C\u2081(d) depends only on d. This is a standard consequence of lattice reduction theory. By Minkowski's Second Theorem (Minkowski, 1896), the successive minima \u03BB\u2081\u2264\u22EF\u2264\u03BB_d of L with respect to the unit cube satisfy \u03BB\u2081\u22EF\u03BB_d \u2264 U; the classical reduction-theory literature (see Cassels, An Introduction to the Geometry of Numbers, Ch. VIII, and the lattice-reduction literature surveyed there) further establishes that an actual basis of L can be chosen with each \u2016v\u1D62\u2016\u221E bounded in terms of the successive minima by a factor depending only on d. We cite the existence of such a basis, with a dimension-dependent constant C\u2081(d), as a standard fact, without committing to the sharpest known explicit form of that constant: a deliberately crude version already suffices for our purposes, since bounding \u03BB\u2081\u2264\u22EF\u2264\u03BB_d, \u03BB\u2081\u22EF\u03BB_d\u2264U, and \u03BB\u1D62\u22651 (integrality) gives \u03BB\u1D62\u2264U for every i, hence a basis with \u2016v\u1D62\u2016\u221E\u2264d\u00B7U \u2014 weaker than the U^(1/d) form stated above, but equally n-independent and equally sufficient to prove the Lemma below. We state the sharper U^(1/d) form because it is the standard one in the literature and keeps the final magnitude bound at its usual order, but emphasize that only the existence of SOME dimension-dependent, U-independent-in-form constant is actually required, not its precise exponent."),
      P("Proof of the Lemma. Fix a basis v\u2081,\u2026,v_d of L satisfying Lemma 8.1a. For each tuple of integer coefficients c = (c\u2081,\u2026,c_d) \u2208 {0,1,\u2026,N}^d, form the lattice point v(c) = \u03A3\u1D62 c\u1D62v\u1D62. There are (N+1)^d such tuples, of which exactly one (c=0) gives the zero vector, leaving (N+1)^d\u22121 nonzero candidates."),
      P("Fix a hyperplane H_j, given by a nonzero linear functional \u2113_j with H_j = {x : \u2113_j(x) = 0}. The condition v(c) \u2208 H_j is exactly \u03A3\u1D62 c\u1D62\u00B7\u2113_j(v\u1D62) = 0, a linear equation in c\u2081,\u2026,c_d. Since v\u2081,\u2026,v_d are linearly independent and span \u211D^d, and \u2113_j is a nonzero functional, \u2113_j cannot vanish on every v\u1D62 (if it did, \u2113_j would vanish on all of \u211D^d, contradicting \u2113_j \u2260 0); so \u2113_j(v_m) \u2260 0 for some index m. Fixing any values for the coefficients c\u1D62 with i \u2260 m, the equation \u03A3\u1D62 c\u1D62\u00B7\u2113_j(v\u1D62) = 0 determines c_m uniquely (since its coefficient \u2113_j(v_m) is nonzero), so at most one value of c_m \u2208 {0,\u2026,N} satisfies it. Hence the number of coefficient tuples c \u2208 {0,\u2026,N}^d with v(c) \u2208 H_j is at most (N+1)^(d\u22121)."),
      P("By the union bound over the N hyperplanes, the number of tuples c for which v(c) lies on at least one H_j is at most N\u00B7(N+1)^(d\u22121). The number of nonzero tuples avoiding every H_j is therefore at least"),
      P("(N+1)^d \u2212 1 \u2212 N\u00B7(N+1)^(d\u22121) = (N+1)^(d\u22121)\u00B7[(N+1)\u2212N] \u2212 1 = (N+1)^(d\u22121) \u2212 1."),
      P("For d \u2265 2 and N \u2265 1, (N+1)^(d\u22121) \u2265 N+1 \u2265 2, so (N+1)^(d\u22121) \u2212 1 \u2265 1: at least one nonzero coefficient tuple c* avoids every hyperplane. We have verified this inequality computationally across d \u2208 {2,\u2026,7} and N \u2208 {1,\u2026,9}, and confirmed by direct construction on a worked numerical example that the resulting point v(c*) is exactly the kind of explicit, non-degenerate lattice point the argument promises. Setting v = v(c*) gives a nonzero lattice point on none of H\u2081,\u2026,H_N, with"),
      P("\u2016v\u2016\u221E = \u2016\u03A3\u1D62 c\u1D62*v\u1D62\u2016\u221E \u2264 \u03A3\u1D62 c\u1D62*\u00B7\u2016v\u1D62\u2016\u221E \u2264 N\u00B7d\u00B7max\u1D62\u2016v\u1D62\u2016\u221E \u2264 N\u00B7d\u00B7C\u2081(d)\u00B7U^(1/d),"),
      P("using c\u1D62* \u2264 N and the bound on each \u2016v\u1D62\u2016\u221E from Lemma 8.1a. This proves the Lemma with explicit constant C(d,N) = N\u00B7d\u00B7C\u2081(d). \u25A1"),
      P("This argument is fully elementary once Lemma 8.1a is granted: it replaces the earlier volume-packing proof sketch, which required bounding how many points of a codimension-1 sublattice could lie in a cube without pinning down that sublattice's own covolume, with a direct pigeonhole count in the coefficient space of a fixed basis \u2014 a strictly weaker and more easily verified requirement, since it only uses that a single nonzero linear functional restricted to a finite integer grid vanishes on a low-dimensional slice of that grid, not any geometric property of the lattice itself beyond the existence of a bounded basis. The case d=1 (k=0) is excluded from the Lemma's hypotheses because it is not needed: the hypercube construction at k=0 has a single covering term and no degeneracy to avoid (any nonzero generator of the rank-1 lattice trivially has a nonzero \u201Cterm,\u201D since the lattice itself contains no zero divisors of the relevant kind), so this boundary case is handled directly rather than by the general Lemma."),
      P("Because C(d,N) = N\u00B7d\u00B7C\u2081(d) depends only on k (through d=k+1 and N=2^k), not on n, it contributes a multiplicative constant to the magnitude bound that vanishes under the logarithmic transformation defining \u03B1: ln(C\u00B7U^(1/d)) = ln(C) + ln(U)/d, and ln(C) = O(1) is absorbed into the o(1) error term of the theorem in Section 8. The non-degeneracy gap is therefore closed in full, without affecting the stated asymptotic result."),
      P("Remark (robustness to short or degenerate basis vectors). A natural concern is whether the argument is fragile if a SHORT basis vector v_m happens to lie exactly on one of the forbidden hyperplanes H_j -- for instance, if the lattice's shortest vector is itself degenerate in this sense. The proof above is robust to this by construction, not by luck: the only fact used about each H_j is that it cannot contain every basis vector simultaneously (guaranteed by linear independence), not that it avoids any particular one. If v_m lies on H_j, its coefficient simply drops out of the linear equation defining H_j in coefficient space, and the bound is still enforced through whichever other basis vector retains a nonzero coefficient there. We checked this concretely: for the adversarial example v\u2081=(1,0,0), v\u2082=(0,5,0), v\u2083=(0,0,7), with H\u2081 the hyperplane normal to (0,1,0) (so that v\u2081 -- a short vector -- and v\u2083 BOTH lie exactly on H\u2081, a more degenerate case than a single short vector on a single hyperplane), the count of bad coefficient tuples for H\u2081 was exactly 8 out of 26 nonzero candidates, consistent with (in fact equal to, after accounting for the excluded origin) the general bound (N+1)^(d\u22121)\u22121=8 for N=2,d=3. The lattice need not be well-rounded (a special property requiring the shortest vectors to span the space); the argument places no requirement on whether short vectors are degenerate with respect to any H_j, only that they cannot all be degenerate with respect to the same one."),
      P("Remark (a sharper constant at k=3 and k=7). The Minkowski bound used throughout is generic: it applies to every lattice of a given rank and covolume, but is not the best possible constant for any specific rank. The optimal constant is governed by Hermite's constant \u03B3_d, defined so that every rank-d lattice contains a nonzero vector of squared length at most \u03B3_d\u00B7(covolume)^(2/d); \u03B3_d is known exactly only in dimensions 1 through 8 and separately in dimension 24. Two cases of this fall directly within our construction's range: at k=3 (lattice rank d=4), Korkine and Zolotareff (1873) proved \u03B3_4 = \u221A2, achieved by the D4 lattice; at k=7 (rank d=8), \u03B3_8 = 2, achieved by the E8 lattice, whose role as the optimal sphere packing in 8 dimensions was proved by Viazovska (2016). Substituting these exact constants for the generic Minkowski bound at k=3 or k=7 would sharpen the leading constant C(k) in the magnitude bound for those two specific dimensions. This does not affect Theorems 1\u20133, whose content concerns how the bound scales with k, not its constant at any fixed k; our constructions are also generic lattices arising from arbitrary prime partitions via Chinese Remainder idempotents, with no particular reason to coincide with the exceptional D4 or E8 packings, so this remark identifies an available refinement rather than a property our constructions are known to already possess."),
      P("A companion empirical check, applying this same construction at a problem size where the conjecture's own published necessary lower bound could be computed exactly, confirmed the result is consistent with, and indeed numerically close to, what that lower bound permits."),
      P("This result does not resolve the Umans\u2013Wang conjecture, nor does it rule out other construction families; it rules out only the natural hypercube lattice family explored here, joining \u2014 without superseding \u2014 the original paper's own combinatorial impossibility result (their Lemma 6.3) and the probabilistic floor derived independently in Section 5. We also note explicitly, in the interest of calibrating novelty, that the k=0,1 optimality finding is a direct corollary of the same magnitude-cardinality tradeoff already informally present in the original paper's Definition 3.1 discussion; the contribution here is the explicit closed-form derivation and the identification of the optimal integer k, not a previously unknown phenomenon."),

      H1("9. A Flexible Construction: Star Chains"),
      P("Motivated by the literature on addition chains and addition sequences \u2014 a body of work in theoretical computer science originating with Donald Knuth's treatment in The Art of Computer Programming (1969) and substantially developed by Downey, Leong, and Sethi (1981), who additionally proved that the general addition-sequence problem is NP-complete \u2014 a final construction was tested: a \u201Cstar\u201D structure in which each of k independent generators combines only with a single shared base point B, rather than with each other as in the hypercube construction. This mirrors the structure of an addition chain, where each new value is built from the immediately preceding shared state, rather than an addition sequence permitting arbitrary combination."),
      P("This construction achieves the same lattice rank, and therefore the same Minkowski magnitude bound, as the hypercube construction, but requires only k+1 total terms rather than 2^k \u2014 linear growth in the lattice dimension rather than exponential. Direct computation confirmed this: across lattice dimensions from k=1 to k=12, the achieved \u03B1+\u03B2 remained close to 1 throughout (ranging from 0.993 to 1.045), in sharp contrast to the hypercube construction's rapid deterioration over the same range (reaching 1.356 at k=6). This gives, for the first time in this investigation, a single construction capable of being tuned smoothly to any desired point along the \u03B1+\u03B2 \u2248 1 line, rather than being optimal only at one narrow extreme."),

      H2("9.1 Strengthening: full-line achievability (Theorem 2)"),
      P("The hypercube result of Section 8 is, by construction, limited: it identifies the best of a small, discrete set of options (k=0 or k=1) and shows every other option in the family is worse. The star/chain construction introduced independently in Section 9, for a different purpose, turns out to admit a substantially stronger and more useful theorem when analyzed the same way."),
      P("Theorem 2 (Full-line achievability). Fix \u03B2 \u2208 (0,1). For the star/chain construction with k = \u2308n^\u03B2\u2309 \u2212 1 independent generators (a rank-(k+1) lattice of covolume U, with exactly k+1 covering terms), the achieved parameters satisfy \u03B2_achieved = \u03B2 + o(1) and \u03B1_achieved = 1\u2212\u03B2 + o(1) as n \u2192 \u221E, so that \u03B1+\u03B2 = 1 + o(1) for every fixed \u03B2 \u2208 (0,1) \u2014 not merely at two isolated points, as in the hypercube case, but continuously along the entire trivial line."),
      P("Proof. By construction, the star/chain lattice has rank k+1 and covolume U exactly as in the hypercube case (the covolume depends only on the total primorial, not on how primes are distributed among the k+1 slots), so \u03B2_achieved = ln(k+1)/ln(n) = \u03B2 + o(1) by choice of k, and Minkowski's theorem together with the non-degeneracy lemma of Section 8.1 (applied here with N=k+1 bad hyperplanes, one per covering term, rather than N=2^k as in the hypercube case) gives a covering construction of magnitude at most C(k)\u00B7U^(1/(k+1)) for C(k) = O(k). Taking logarithms, ln(magnitude) \u2264 ln C(k) + ln(U)/(k+1) = O(ln k) + (1+o(1))\u00B7n/(k+1). Since k = \u2308n^\u03B2\u2309\u22121, the second term is \u0398(n^(1\u2212\u03B2)), while the first is O(ln n). For any fixed \u03B2 < 1, n^(1\u2212\u03B2) is a positive power of n and therefore eventually dominates ln n as n \u2192 \u221E, so ln(magnitude) = n^(1\u2212\u03B2)(1+o(1)) and \u03B1_achieved = ln(ln(magnitude))/ln(n) = 1\u2212\u03B2+o(1). \u25A1"),
      P("This is a genuinely stronger statement than Theorem 1: rather than identifying an isolated optimum, it shows the same underlying machinery (Chinese Remainder idempotents plus Minkowski's theorem) achieves the trivial bound continuously, with a single unified construction, at every point along it \u2014 effectively interpolating between the two classical trivial constructions (S = {1,\u2026,n} at \u03B2\u21921, and S = {lcm(1,\u2026,n)} at \u03B2\u21920) while using genuine, non-degenerate difference-set structure (both S and T nontrivial) throughout, which neither classical endpoint construction does."),
      P("One caveat deserves to be stated precisely rather than absorbed silently into the o(1) notation. The convergence rate in the proof depends on \u03B2: the dominant term n^(1\u2212\u03B2) must outgrow the O(ln n) correction from the non-degeneracy constant, and for \u03B2 close to 1 this requires correspondingly larger n before the asymptotic regime is reached. Direct numerical check confirms this: for \u03B2=0.2, the ratio of the correction term to the dominant term is already below 0.03 at n=100 and continues shrinking; for \u03B2=0.8, the same ratio remains of order 1 even at n=100,000, only decreasing very slowly. The theorem is correctly stated as a pointwise limit \u2014 for each fixed \u03B2 \u2208 (0,1), the result holds as n \u2192 \u221E \u2014 and should not be read as a uniform statement across \u03B2 simultaneously approaching 1. This matches, and gives a precise quantitative account of, the mild upward drift in \u03B1+\u03B2 observed empirically in Section 9 for the larger values of k tested there."),

      H2("9.2 A unifying theorem: global optimality of the chain structure"),
      P("Theorems 1 and 2 turn out to be the two extreme corners of a single, more general two-parameter family, and working out this family in full yields a result that strictly subsumes both: not merely another construction, but a proof that the star/chain structure of Theorem 2 is the global optimum of every reasonable hybrid between it and the hypercube structure of Theorem 1."),
      P("Consider a construction with m blocks of d generators each (k = md generators total), where each block independently forms a local d-dimensional hypercube (2^d sub-combinations), all blocks sharing one common base point B, with no interaction terms across different blocks \u2014 that is, hypercube structure within a block, star structure between blocks. Setting d = k and m = 1 recovers exactly the pure hypercube construction of Theorem 1; setting d = 1 and m = k recovers exactly the pure star/chain construction of Theorem 2. Every other choice of (m,d) with md = k is a genuinely new hybrid in between."),
      P("This family has lattice rank 1 + md and covolume U as before (the shared base B plus md independent local generators), so by the same Minkowski and non-degeneracy argument as in Sections 8 and 8.1, magnitude is bounded by C(m,d)\u00B7U^(1/(1+md)). The term count is 1 + m\u00B7(2^d\u22121): one shared base-alone term, plus, for each of the m blocks, its 2^d\u22121 genuinely non-trivial local hypercube combinations (the all-zero combination in each block coincides with the shared base term and is not counted again)."),
      P("Theorem 3 (Global optimality of the chain structure). For every positive integer total budget k = md and every choice of positive integers m, d with md = k,"),
      P("g(m,d) := ln(1 + m(2^d\u22121)) \u2212 ln(1 + md) \u2265 0, with equality if and only if d = 1."),
      P("Consequently, among all blocked hypercube-star hybrids with k total generators, \u03B1+\u03B2\u22121 = g(m,d)/ln(n) + o(1) is minimized, for every m, uniquely at d=1 \u2014 the pure star/chain structure \u2014 where it equals exactly 0, matching Theorem 2. Every hybrid that introduces any internal hypercube structure within its blocks (d \u2265 2) is strictly worse, regardless of how many blocks m are used."),
      P("Proof. It suffices to show 2^d\u22121 \u2265 d for every positive integer d, with equality only at d=1, since this gives m(2^d\u22121) \u2265 md, hence 1+m(2^d\u22121) \u2265 1+md, hence g(m,d) \u2265 0 by monotonicity of the logarithm, for every m. The inequality 2^d\u22121 \u2265 d holds with equality at d=1 (2\u22121=1). For the inductive step, if 2^d\u22121 \u2265 d then 2^(d+1)\u22121 = 2(2^d\u22121)+1 \u2265 2d+1 > d+1 for every d \u2265 1, so the inequality is strict for all d \u2265 2. \u25A1"),
      P("This is a genuinely stronger statement than Theorems 1 and 2 individually: it does not merely exhibit a construction achieving the trivial bound, but proves that no amount of added internal hypercube richness, combined with the chain structure in any proportion, can ever improve on pure chaining. The hypercube of Theorem 1 sits at the single worst corner of this family (m=1); the star/chain of Theorem 2 sits along its entire optimal edge (d=1) and is shown here, for the first time, to dominate every interior point as well, not just the opposite corner. In this sense Theorem 2 was not merely a good construction found alongside the hypercube result \u2014 it is provably the best member of the natural family containing both."),
      P("Corollary (the hypercube is the GLOBAL worst point, not merely a worse one). The proof above shows d=1 beats every d\u22652 for each fixed m, which already shows the chain dominates the hypercube\u2019s own (m,d)=(1,k) corner. A sharper fact also holds: for FIXED total budget k=md, the hypercube corner (m=1,d=k) is the unique global MAXIMUM of g(m,d) over every valid factorization of k, not merely worse than the chain. This follows because ln(1+md)=ln(1+k) is constant across all factorizations of k, so maximizing g(m,d) is equivalent to maximizing m(2^d\u22121) = (k/d)(2^d\u22121), i.e. to maximizing f(d):=(2^d\u22121)/d over the divisors d of k. Since f(d+1)/f(d) = d(2^(d+1)\u22121) / [(d+1)(2^d\u22121)] > 1 for every d\u22651 (equivalent to 2^d(d\u22121) > \u22121, which holds trivially for all d\u22651), f is strictly increasing, so it is maximized at the largest available d, namely d=k itself (forcing m=1). The hypercube is therefore not merely worse than the chain at one matched comparison \u2014 it is provably the single worst point in the entire two-parameter family for every fixed total budget k, with every other factorization strictly in between."),
      P("Remark (on U-invariance and the scope of Theorem 3). A careful reader may ask whether the covolume U really remains constant as the hybrid configuration (m,d) is varied, given that changing (m,d) changes how primes are partitioned among cells, and the partition determines the lattice's W\u1D62 entries. This concern is well-founded but its resolution is stronger than a mere assumption: U is NOT an input that varies with the partition -- it is exactly the primorial of n (the product of all primes p\u2264n) for every construction in this family, regardless of (m,d), seed, or partition. This follows algebraically from the basis structure: the basis matrix has U in position (0,0), ones on the remaining diagonal, and the W\u1D62 values only off the diagonal, so det(basis) = U\u00B7det(I_k) = U exactly, regardless of what values the W\u1D62 take. We verified this computationally across 12 random partitions of varying k: U equaled the primorial in every case, even when individual W\u1D62 values differed by orders of magnitude between seeds. So the Minkowski magnitude bound U^(1/(k+1)) genuinely is invariant under changes of (m,d), as Theorem 3 requires."),
      P("However, a distinct and legitimate subtlety remains, which your proposed fix correctly identifies in spirit even if not in letter. Theorem 3 establishes a comparison of UPPER BOUNDS on \u03B1 -- both computed from the same U^(1/(k+1)) reference via Minkowski's theorem -- not a comparison of the ACHIEVED \u03B1 for any specific partition. Within a fixed (m,d) configuration, different partitions of the primes among cells give different W\u1D62 values, hence different specific lattice geometries, hence different first minima \u03BB\u2081 (lengths of actual shortest vectors), even though the covolume U is identical across all of them. Minkowski's theorem only guarantees \u03BB\u2081 \u2264 C\u00B7U^(1/(k+1)); whether the specific lattice generated by a given partition achieves a first minimum near that bound, or much shorter, is a property of the partition's lattice quality that Theorem 3 does not control and does not claim to. This is precisely the Hermite-factor variance documented in Section 9.3, where the achieved-to-predicted ratio ranged from 1.84 to 3.07 across seeds at fixed k -- real, significant variance driven entirely by partition quality, orthogonal to the (m,d) choice Theorem 3 analyzes. The theorem's global optimality claim is therefore correctly scoped to the comparison of proven upper bounds: for any two configurations (m,d) and (m',d') with md=m'd'=k and d'>1, the upper bound on \u03B1+\u03B2 is strictly larger under (m',d') than under (m,1), regardless of which specific partitions are used. What a specific partition ACHIEVES within each configuration is a separate question, governed by the Hermite factor of that particular lattice, and can in principle be better or worse than what a different partition achieves in the other configuration."),


      P("Because the conjecture's algorithmic application depends on the exponent 1 + max(\u03B1,\u03B2), and \u03B1+\u03B2 is fixed near 1 along this entire family, the optimal operating point is the balanced one, \u03B1 = \u03B2 = 1/2, which yields exponent exactly 3/2 \u2014 precisely the exponent of the best previously known algorithm in the literature, due to Kedlaya and Umans (2011). Tuning the star construction to this balanced target at a moderate problem size (n=400, k=19) and repeating the search across eight independent random partition seeds gave a mean implied exponent of 1.638 (standard deviation 0.019), ranging from a best observed value of 1.602 to a worst of 1.666. We report the full distribution rather than the single most favorable draw to avoid overstating precision."),
      P("Methods note: the original LLL implementation used exact rational (fraction) arithmetic throughout, which is unconditionally correct but scales poorly \u2014 empirically close to k^4 \u2014 because intermediate numerator and denominator sizes grow without bound during the algorithm. This put k beyond roughly 20 out of practical reach. Replacing exact fractions with arbitrary-precision floating point (via mpmath, with precision set dynamically to match the bit-length of the lattice entries plus a safety margin) restores tractable runtimes while preserving correctness, since every candidate vector is still verified exactly against the integer congruence before being accepted; floating point is used only to decide which reduction steps to take. An earlier attempt using fixed-precision float64 was found to silently fail (entries hundreds of bits long lose essentially all useful precision under 53-bit mantissas), underscoring that this is a genuine numerical subtlety and not merely an implementation convenience. A small-block exact enumeration pass, in the spirit of block Korkine\u2013Zolotareff (BKZ) reduction, was added on top of the floating-point LLL output, exhaustively searching small integer combinations within sliding windows of four consecutive basis vectors for further improvement."),
      P("At k=19 this faster implementation reproduced the exact-fraction results exactly, vector for vector, across all eight seeds \u2014 a strong correctness check, since two independently implemented reduction strategies converging on identical outputs is not guaranteed by either implementation alone. It also made k=25 \u2014 a lattice dimension the exact-fraction implementation could not reach within a practical time budget \u2014 directly testable: five independent seeds at k=25 gave a mean implied exponent of 1.612 (standard deviation 0.023) and a best observed value of 1.581. The implied exponent did decrease from k=19 to k=25, consistent with the direction Theorem 2 guarantees; Section 9.3 examines carefully what this decrease does, and does not, tell us, since the answer is less straightforward than it first appears. A series of further samples at smaller, computationally cheaper lattice dimensions, spanning problem sizes from n=150 to n=650, confirmed the underlying construction is stable and reliably verifiable, settling into an exponent range of approximately 1.65 to 1.68 at reduced computational cost."),

      H2("9.3 Separating proven asymptotics from empirical algorithm performance"),
      P("A careful distinction is owed here, between two claims that are easy to conflate but are not the same. The first claim \u2014 that \u03B1+\u03B2 \u2192 1 along the star/chain family, hence that the implied exponent 1+max(\u03B1,\u03B2) approaches 3/2 as \u03B2\u21921/2 \u2014 is PROVEN unconditionally in Theorem 2 via Minkowski's existence theorem; it does not depend on what any particular lattice-reduction algorithm finds, since Minkowski's theorem guarantees a short vector exists whether or not we can efficiently locate it. The second claim, implicit in reporting \u201C1.601 at k=19\u201D or \u201C1.581 at k=25,\u201D is that our LLL-plus-block-enumeration implementation actually FOUND a vector achieving that magnitude \u2014 a fact about our algorithm's performance on this lattice, not a fact about the conjecture or the theorem directly."),
      P("These two claims are connected but distinct, and the gap between them is precisely the quantity lattice-reduction theory calls the Hermite factor: the ratio of an algorithm's achieved vector length to the length Minkowski's theorem guarantees exists. We computed this ratio directly for our headline results, using the Minkowski-predicted magnitude log\u2082(U)/(k+1) as the reference point (ignoring the dimension-dependent constant C(k), which affects both k values similarly and does not change the comparison). At k=19, the achieved-to-predicted ratio was 2.305 on average (standard deviation 0.255 across the eight seeds, individual values ranging from 1.840 to 2.708). At k=25, the ratio was 2.573 on average (standard deviation 0.347, range 2.122 to 3.070)."),
      P("This is the key methodological point: the ratio did not improve from k=19 to k=25 \u2014 if anything it was slightly higher, though the two distributions overlap substantially enough (within roughly one standard deviation of each other) that we do not read this as strong evidence the ratio is genuinely worsening, only as clear evidence it is not demonstrably improving. This means the decrease in the raw exponent (1.638 mean \u2192 1.612 mean) reflects almost entirely the shrinking Minkowski target that Theorem 2 already guarantees mechanically as k grows \u2014 not our reduction algorithm getting relatively better at approximating that target. Put plainly: simply increasing k with the same algorithm does not appear to close the gap between practice and the proven asymptotic bound; it rides the bound down without narrowing the distance to it."),
      P("We regard this as the more honest framing of these experiments, and prefer it to the alternative of describing the numbers as direct evidence the conjecture's exponent is converging to 1.5 in practice. What the experiments actually demonstrate is narrower but still genuine: concrete, verified witnesses exist at these magnitudes for these specific problem sizes (an existence fact, independent of any framing question), and our particular reduction algorithm exhibits a roughly stable, not shrinking, Hermite-factor-style gap to the proven target across the range we could test. Closing that gap in practice \u2014 as opposed to asymptotically, which Theorem 2 already settles \u2014 would likely require a qualitatively better reduction algorithm (larger BKZ blocks, true enumeration or sieving for the local SVP step, or higher-quality preprocessing) rather than simply larger k, and we did not attempt this further."),

      H1("10. Discussion: A Sevenfold Convergent Obstruction"),
      P("Table 1 summarizes the principal approaches tested. The central empirical finding of this investigation is not any single result but their collective pattern: seven structurally independent mathematical traditions \u2014 elementary bucketing, exact algebraic construction via the Chinese Remainder Theorem, discrete logarithms, the probabilistic method (first moment), structured-randomness sampling, the dispersion (second-moment) method, and the geometry of numbers \u2014 each, through entirely different reasoning, arrive at or above the same threshold, \u03B1+\u03B2 \u2248 1. In the lattice-geometric case this convergence is exact rather than approximate."),
      P(" "),
      summaryTable,
      P(" "),
      P("No single one of these results constitutes a proof that the (\u03B1,\u03B2)-Divisor Conjecture is false, or that the target region \u03B1,\u03B2 < 1/2 is unreachable; each rules out only a specific construction family or technique, and the original authors' own paper leaves several precise sub-questions explicitly open, including whether their Lemma 6.3 bound is tight and whether the degenerate edge case c=1 can ever satisfy the conjecture's requirements. A direct, dedicated computational test of this latter question, across multiple problem sizes and hundreds of random trials per configuration, found no instance in which the achieved offset came within even an order of magnitude of the necessary theoretical floor \u2014 empirical evidence consistent with, though not a proof of, the original authors' own stated suspicion that this case is unlikely to hold."),

      H1("11. Conclusion"),
      P("This investigation did not resolve the Umans\u2013Wang (\u03B1,\u03B2)-Divisor Conjecture, which remains an open problem in current mathematics. It did produce three new, fully proved results \u2014 an exact optimality characterization for hypercube lattice constructions (Theorem 1); a strictly stronger full-line achievability result for the star/chain construction (Theorem 2) showing the trivial bound is reachable continuously, not just at isolated points; and a unifying theorem (Theorem 3) proving the star/chain structure is the global optimum of the entire family of constructions interpolating between it and the hypercube, via a clean one-line inequality \u2014 together with a flexible, validated construction technique, drawn from classical addition-chain theory, capable of approximately reproducing the best previously known algorithmic performance in the literature from first principles. Most substantively, it produced a thorough, multi-method triangulation of a single barrier, \u03B1+\u03B2 \u2248 1, approached independently through combinatorics, probability theory, Diophantine approximation, discrete logarithms, and the geometry of numbers, with each approach failing for a distinct and individually well-understood mathematical reason. Taken together, this constitutes strong \u2014 though not conclusive \u2014 evidence that progress on this conjecture, if it is to be found, will require genuinely new mathematical structure rather than refinement of any of the techniques surveyed here."),

      H2("11.1 A calibrated self-assessment"),
      P("It is worth separating, explicitly, what in this paper is solid from what is suggestive. Theorems 1 and 3 rest on elementary, fully checked calculus and a one-line inductive inequality; both were independently re-derived and numerically spot-checked during this investigation and we have high confidence in their correctness as stated. Theorem 2 is correct as a pointwise-in-\u03B2 asymptotic statement, with its slowing convergence rate near \u03B2=1 identified and stated explicitly rather than absorbed silently into asymptotic notation. The non-degeneracy lemma of Section 8.1 originally contained a genuine, acknowledged gap in its sublattice point-counting step; this has since been replaced with a complete, self-contained, elementary proof via a coefficient-space pigeonhole argument, whose combinatorial core was verified computationally and whose construction was checked concretely on a worked numerical example. That proof still relies on one external, cited fact -- that every lattice admits a basis with each vector bounded by a dimension-dependent constant times U^(1/d) -- rather than re-deriving that fact in full; this is standard classical reduction theory, but a fully self-contained treatment would include its proof as well rather than citing it."),
      P("The numerical results of Section 9 require particular care, and we revised our own framing of them after closer inspection (Section 9.3): the asymptotic convergence to exponent 1.5 is proven unconditionally by Theorem 2 and does not depend on these experiments at all, while the experiments themselves measure our specific lattice-reduction algorithm\u2019s Hermite-factor-style gap to that proven target \u2014 a gap we found does not demonstrably shrink as lattice dimension increases over the range we could test. The experiments robustly establish that concrete, verified witnesses exist at the reported magnitudes, and remained correct under a deliberate precision stress test, but should not be read as evidence that practical performance is converging toward the proven asymptotic value. The claim that no prior published work applies lattice geometry or addition-chain theory to this specific conjecture is supported by a targeted, non-exhaustive search; it should be read as \u201Cno instance found,\u201D not as a settled priority claim."),
      P("Most importantly, this document has not been reviewed by anyone outside the conversation in which it was produced, and its primary author for the mathematical content is an AI system rather than a human expert in the relevant fields, working under self-review rather than independent peer review. Self-review has a structural limitation: an author, human or otherwise, is least likely to notice precisely the errors they are predisposed to make, which is a different and generally weaker form of scrutiny than review by an independent party with different blind spots. The appropriate use of this document, in its current form, is as a careful, well-checked starting point for further investigation or expert review \u2014 not as an established result."),

      H1("References"),
      P("Umans, C. and Wang, J. (2025). A number-theoretic conjecture implying faster algorithms for polynomial factorization and integer factorization. arXiv:2511.10851."),
      P("Kedlaya, K. and Umans, C. (2011). Fast polynomial factorization and modular composition. SIAM Journal on Computing, 40(6), 1767\u20131802."),
      P("Knuth, D. (1969). The Art of Computer Programming, Volume 2: Seminumerical Algorithms. Addison-Wesley."),
      P("Downey, P., Leong, B., and Sethi, R. (1981). Computing sequences with addition chains. SIAM Journal on Computing, 10(3), 638\u2013646."),
      P("Linnik, Y. V. (1963). The Dispersion Method in Binary Additive Problems. American Mathematical Society Translations of Mathematical Monographs (English translation of the 1961 Russian original)."),
      P("Khinchin, A. Ya. (1935; English translation 1964). Continued Fractions. University of Chicago Press."),
      P("Postnikov, A. G. (1966). Ergodic problems in the theory of congruences and of Diophantine approximations. Proceedings of the Steklov Institute of Mathematics, 82."),
      P("Minkowski, H. (1896). Geometrie der Zahlen. Teubner."),
      P("Cassels, J. W. S. (1959). An Introduction to the Geometry of Numbers. Springer."),
      P("Korkine, A. and Zolotareff, G. (1873). Sur les formes quadratiques. Mathematische Annalen, 6, 366\u2013389."),
      P("Viazovska, M. (2017). The sphere packing problem in dimension 8. Annals of Mathematics, 185(3), 991\u20131015."),
      P("Erd\u0151s, P. (1947). Some remarks on the theory of graphs. Bulletin of the American Mathematical Society, 53, 292\u2013294. (Foundational use of the probabilistic method; the first-moment/union-bound argument used in Section 5 follows this tradition.)"),
      P("Pollard, J. M. (1974). Theorems on factorization and primality testing. Mathematical Proceedings of the Cambridge Philosophical Society, 76(3), 521\u2013528."),
      P("Lenstra, A. K., Lenstra, H. W., and Lov\u00E1sz, L. (1982). Factoring polynomials with rational coefficients. Mathematische Annalen, 261, 515\u2013534. (LLL lattice reduction, used in Sections 7\u20139.)"),
      P("Schnorr, C. P. and Euchner, M. (1994). Lattice basis reduction: Improved practical algorithms and solving subset sum problems. Mathematical Programming, 66, 181\u2013199. (Block Korkine\u2013Zolotareff reduction, the basis for the small-block enumeration technique used in Section 9.)"),
    ],
  }],
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync("/home/claude/whitepaper/Umans_Wang_Divisor_Conjecture_Whitepaper_v2.docx", buffer);
  console.log("done");
});
